var Mocha = require('mocha');

var mocha = new Mocha({
  reporter: 'json'
});
mocha.addFile('/Users/mars/fusemachines/tutorial/javascript/node/mocha/test-prep/src/tests/t1.js');

/**
 * run the test and print 0 for failed test and 1 for passed
 * @returns Promise<{ status: string, score: number }>
 */
function main() {

  return new Promise(resolve => {

    mocha.run()
      .on('start', function () {
        // do something
        console.log('Starting');
      })
      .on('pass', function (test, success) {
        // I want to resolve the promise with the result generated by mocha:
        // console.log('knbjjbkjbbkjb', test, this.testResults);
        let status = 'Succeded';
        return resolve({ status, score: 1 });
      })
      .on('fail', function (test, error) {
        // I want to resolve the promise with the result generated by mocha:
        // console.error(error);
        let status = 'Failed';
        return resolve({ status, score: 0 });
      })
      // ...
      .on('end', function () {
        // I want to resolve the promise with the result generated by mocha:
        // console.log(this.testResults);
        // console.log(test, result);
      });

  });

}
// here we run the test runner
main().then(result => console.log(result));
