// nodejs = v6.9.4
'use strict';
var Mocha = require('mocha');

var mocha = new Mocha({
  reporter: 'json'
});
mocha.addFile('/Users/mars/fusemachines/tutorial/javascript/node/mocha/test-prep/src/tests/t1.js');

/**
 * run the test and print 0 for failed test and 1 for passed
 * @returns Promise<{ status: string, score: number }>
 */
function main() {
  return new Promise(resolve => {

    mocha.run()
      .on('test', function(){
        console.log('Starting...');
      })
      .on('pass', function (test, success) {
        // I want to resolve the promise with the result generated by mocha:
        let status = 'Succeded', score = 1;
        return resolve({ status, score });
      })
      .on('fail', function (test, error) {
        // I want to resolve the promise with the result generated by mocha:
        let status = 'Failed', score = 0;
        return resolve({ status, score });
      })
      .on('test end', function(){
        console.log('Finishing...');
      });

  });
}
// here we run the test runner
main().then(result => console.log(result));
